name: CD - Staging

on:
  push:
    branches:
      - staging

jobs:
  cd-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render - Staging
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_STAGING_URL }}"
          echo "Deployment triggered for Staging environment on Render"
